import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {singleFlight} from '../lib/session-tools.mjs';
function api(fetch){const output=ts.transpileModule(fs.readFileSync('lib/api.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(output,{module,exports:module.exports,require:name=>name==='expo-secure-store'?{}:name==='react-native'?{Platform:{OS:'web'}}:{singleFlight},process:{env:{EXPO_PUBLIC_SUPABASE_URL:'https://fixture.example',EXPO_PUBLIC_SUPABASE_ANON_KEY:'public'}},__DEV__:false,fetch,AbortController,setTimeout,clearTimeout,Date,JSON,Error,Set});return module.exports;}
const reply=(body,status=200)=>({ok:status<400,text:async()=>JSON.stringify(body)});
test('active parent authenticates; expired session refreshes once before concurrent reads',async()=>{let refresh=0;const client=api(async path=>{if(path.includes('grant_type=password'))return reply({access_token:'old',refresh_token:'r',expires_in:0,user:{id:'u'}});if(path.includes('refresh_token')){refresh++;return reply({access_token:'new',refresh_token:'r',expires_in:3600,user:{id:'u'}})}if(path.includes('/profiles'))return reply([{full_name:'Parent',role:'guardian',is_active:true,account_status:'active'}]);return reply([])});await client.login('parent@example.test','password');await Promise.all([client.request('/rest/v1/invoices'),client.request('/rest/v1/invoices')]);assert.equal(refresh,1);assert.equal(client.currentSession().access_token,'new');});
test('inactive or non-family profiles never retain session',async()=>{const client=api(async path=>path.includes('/profiles')?reply([{full_name:'Student',role:'student',is_active:true,account_status:'active'}]):reply({access_token:'x',refresh_token:'r',expires_in:3600,user:{id:'u'}}));await assert.rejects(client.login('x@example.test','password'),/active family/);assert.equal(client.currentSession(),null);});
test('failed refresh removes the session',async()=>{const client=api(async path=>path.includes('refresh_token')?reply({message:'Expired'},400):path.includes('/profiles')?reply([{full_name:'Parent',role:'parent',is_active:true,account_status:'active'}]):reply({access_token:'x',refresh_token:'r',expires_in:0,user:{id:'u'}}));await client.login('x@example.test','password');await assert.rejects(client.request('/rest/v1/invoices'),/Expired/);assert.equal(client.currentSession(),null);});
test('logout invalidates a delayed login result',async()=>{let release;const gate=new Promise(r=>release=r);const client=api(async path=>{if(path.includes('grant_type=password')){await gate;return reply({access_token:'late',refresh_token:'r',expires_in:3600,user:{id:'u'}})}if(path.includes('/profiles'))return reply([{full_name:'Parent',role:'parent',is_active:true,account_status:'active'}]);return reply(null)});const pending=client.login('a@example.test','password');await client.logout();release();await pending.catch(()=>{});assert.equal(client.currentSession(),null);});
