import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {singleFlight} from '../lib/session-tools.mjs';
function api(fetch, secureStore={}, platform='web'){const output=ts.transpileModule(fs.readFileSync('lib/api.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(output,{module,exports:module.exports,require:name=>name==='expo-secure-store'?secureStore:name==='react-native'?{Platform:{OS:platform}}:{singleFlight},process:{env:{EXPO_PUBLIC_SUPABASE_URL:'https://fixture.example',EXPO_PUBLIC_SUPABASE_ANON_KEY:'public'}},__DEV__:false,fetch,AbortController,setTimeout,clearTimeout,Date,JSON,Error,Set});return module.exports;}
const reply=(body,status=200)=>({ok:status<400,text:async()=>JSON.stringify(body)});
test('active parent authenticates; expired session refreshes once before concurrent reads',async()=>{let refresh=0;const client=api(async path=>{if(path.includes('grant_type=password'))return reply({access_token:'old',refresh_token:'r',expires_in:0,user:{id:'u'}});if(path.includes('refresh_token')){refresh++;return reply({access_token:'new',refresh_token:'r',expires_in:3600,user:{id:'u'}})}if(path.includes('/profiles'))return reply([{full_name:'Parent',role:'guardian',is_active:true,account_status:'active'}]);return reply([])});await client.login('parent@example.test','password');await Promise.all([client.request('/rest/v1/invoices'),client.request('/rest/v1/invoices')]);assert.equal(refresh,1);assert.equal(client.currentSession().access_token,'new');});
test('inactive or non-family profiles never retain session',async()=>{const client=api(async path=>path.includes('/profiles')?reply([{full_name:'Student',role:'student',is_active:true,account_status:'active'}]):reply({access_token:'x',refresh_token:'r',expires_in:3600,user:{id:'u'}}));await assert.rejects(client.login('x@example.test','password'),/active family/);assert.equal(client.currentSession(),null);});
test('failed refresh removes the session',async()=>{const client=api(async path=>path.includes('refresh_token')?reply({message:'Expired'},400):path.includes('/profiles')?reply([{full_name:'Parent',role:'parent',is_active:true,account_status:'active'}]):reply({access_token:'x',refresh_token:'r',expires_in:0,user:{id:'u'}}));await client.login('x@example.test','password');await assert.rejects(client.request('/rest/v1/invoices'),/Expired/);assert.equal(client.currentSession(),null);});
test('logout invalidates a delayed login result',async()=>{let release;const gate=new Promise(r=>release=r);const client=api(async path=>{if(path.includes('grant_type=password')){await gate;return reply({access_token:'late',refresh_token:'r',expires_in:3600,user:{id:'u'}})}if(path.includes('/profiles'))return reply([{full_name:'Parent',role:'parent',is_active:true,account_status:'active'}]);return reply(null)});const pending=client.login('a@example.test','password');await client.logout();release();await pending.catch(()=>{});assert.equal(client.currentSession(),null);});
test('plain text server errors remain readable',async()=>{const client=api(async()=>({ok:false,text:async()=>'Gateway unavailable'}));await assert.rejects(client.request('/rest/v1/invoices'),/^Error: Gateway unavailable$/);});


const parent=()=>reply([{full_name:'Parent',role:'parent',is_active:true,account_status:'active'}]);
const token=id=>reply({access_token:id,refresh_token:'r',expires_in:3600,user:{id}});
test('delayed native restore cannot undo logout',async()=>{let release;const gate=new Promise(r=>release=r);const client=api(async path=>path.includes('/profiles')?parent():token('old'),{getItemAsync:async()=>{await gate;return JSON.stringify({access_token:'old',refresh_token:'r',expires_at:Date.now()+3600000,user:{id:'old'}})},deleteItemAsync:async()=>{},setItemAsync:async()=>{}},'ios');const pending=client.restoreSession();await client.logout();release();await pending;assert.equal(client.currentSession(),null);});
test('old logout completion cannot clear a newer login',async()=>{let release;const gate=new Promise(r=>release=r);const client=api(async path=>path.includes('/logout')?(await gate,reply(null)):path.includes('/profiles')?parent():token('new'));await client.login('a','password');const pending=client.logout();await client.login('b','password');release();await pending;assert.equal(client.currentSession()?.access_token,'new');});
test('recovery unmounted during profile validation cannot authenticate',async()=>{let release,active=true;const gate=new Promise(r=>release=r);const client=api(async path=>path.includes('/profiles')?(await gate,parent()):reply({id:'u'}));const pending=client.acceptRecovery('a','r',()=>active);await new Promise(r=>setTimeout(r,0));active=false;release();await pending.catch(()=>{});assert.equal(client.currentSession(),null);});
test('stale refresh failure cannot clear a newer login',async()=>{let release,count=0;const gate=new Promise(r=>release=r);const client=api(async path=>{if(path.includes('grant_type=password'))return reply({access_token:++count===1?'old':'new',refresh_token:'r',expires_in:count===1?0:3600,user:{id:'u'}});if(path.includes('refresh_token')){await gate;return reply({message:'Expired'},400)}return parent()});await client.login('a','password');const pending=client.request('/rest/v1/invoices').catch(()=>{});await new Promise(r=>setTimeout(r,0));await client.login('b','password');release();await pending;assert.equal(client.currentSession()?.access_token,'new');});
test('native writes remain ordered when logout interrupts persistence',async()=>{let release,disk,started;const gate=new Promise(r=>release=r),writing=new Promise(r=>started=r);const client=api(async path=>path.includes('/profiles')?parent():token('u'),{setItemAsync:async(_key,value)=>{started();await gate;disk=value},deleteItemAsync:async()=>{disk=null}},'ios');const pending=client.login('a','password');await writing;const leaving=client.logout();assert.equal(client.currentSession(),null);release();await Promise.all([pending,leaving]);assert.equal(disk,null);});
